### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by nuschk** [GoogleCloudPlatform/psq#13]
We're currently looking into migrating to gke from a managed vserver, where we're running celery on rabbitmq and redis. We don't have very elaborate requirements for delayed task execution: the usual delayed tasks, a few cron jobs and a couple of long running background tasks. 

PSQ looks very interesting as thin layer above pub/sub. My question is: is it considered ready for production? Is anyone using it already?

Also related: What's the best way to use it in CI for testing? In RQ for example, we can declare a queue as synchronous with 

    Queue('low', async=False)

and thus don't need to handle any workers, which seems handy (I haven't used it, though). Or should I just use the gcloud emulator, which *should* work if I'm not mistaken, but brings its fair set of complications to testing, as we'd need to spin up some workers.

Thanks!

**Comment by jonparrott** [comment]
Hi @nuschk! PSQ is not an official Google product, it's intended as an example of how to achieve one use case using Pub/Sub. If you decide to use it in production support falls on you. Of course, if there are issues with Pub/Sub itself then that is a different story.

That said, it's a relatively small library (one developer could conceivably understand all of it in one or two days) and can be used as a good starting point for creating your own library. If you're interested in a out-of-the-box production-ready task queue service, you might want to sign up for our [Cloud Tasks alpha](https://goo.gl/Ya0AZd).

> What's the best way to use it in CI for testing?

You can use the emulator and run a worker if you want. You can also just manually call [`queue.deque`](https://github.com/GoogleCloudPlatform/psq/blob/master/psq/queue.py#L98) yourself to inspect the tasks that were queue and even [execute them](https://github.com/GoogleCloudPlatform/psq/blob/master/psq/worker.py#L67) if you want. If you have a specific way you'd like to do testing with this, I'd love to see an issue/pull request to add it. :)

(I'm closing this issue, but feel free to continue to comment if you have more questions).

**Comment by nuschk** [comment]
Hey @jonparrott , thanks for your reply.

I'm aware of psq not being an official product, and am fine with it. As you say, the code base is small and seems pretty solid to me, as far as I can tell.

I'm probably going to implement the async flag myself. Staying close to RQ's API is in the spirit of this library, I guess. If I do, I could certainly do a PR for it. 

Cloud functions are certainly interesting, but a bit too much for the moment. I'm looking for a low-profile replacement of our celery stuff. There's a bunch of other things that need to be fixed in order to get to gcloud, so that will have to be taken care of first. Hopefully later! :-)
