### ISSUE TITLE
Graceful shutdown for in-process Worker

### ISSUE THREAD

**Issue by nuschk** [GoogleCloudPlatform/psq#17]
I think it would be sensible to use the graceful shutdown scheme used in MultiprocessWorker (stop gracefully when receiving a SIGINT, finishing a running task, stop forcefully on second signal) also for the in-process Worker.

I could make a PR for that as well.

**Comment by jonparrott** [comment]
> I could make a PR for that as well.

PRs welcome. :)

**Comment by jonparrott** [comment]
The multiprocessing worker has been removed in #34.
