### ISSUE TITLE
When using storage, it goes into a death spiral

### ISSUE THREAD

**Issue by jcoatgoogle** [GoogleCloudPlatform/psq#18]
I have the following code

```
import psq
from google.cloud import datastore, pubsub
PROJECT_ID='thisisavalidproject'

def adder(a, b):
  return a + b

if __name__ == '__main__':
  pubsub_client = pubsub.Client(project=PROJECT_ID)
  ds_client = datastore.Client(PROJECT_ID)
  q = psq.Queue(pubsub_client, storage=psq.DatastoreStorage(ds_client))
  r = q.enqueue(adder, 5, 6)
  print(r.result())
```

with the following requirements.txt

```
google-cloud==0.20.0
psq==0.5.0
```

When I run this, it just dies. Having inspected the traffic a little, it just keeps doing storage lookups.

**Comment by jonparrott** [comment]
@jcoatgoogle do you have a worker running to process the tasks? `r.result()` will indeed block until the result is available, so if no worker ever process the task the result will never be available.

**Comment by jcoatgoogle** [comment]
I figured that was the case... perhaps the example needs to be a bit clearer. Rereading it, it's not clear when the piece consuming and doing the processing is instantiated?

**Comment by jonparrott** [comment]
@jcoatgoogle Ah yeah, we should probably add a README to the examples folder. If you want to send a PR to add that, please do.
