### ISSUE TITLE
Working around abysmal google.cloud.pubsub.Subscription.pull() delays?

### ISSUE THREAD

**Issue by wlongabaugh** [GoogleCloudPlatform/psq#24]
So I'm using psq in a light-demand environment, and am encountering abysmal latency on the workers pulling jobs off the queue. As in 10 minutes when things are "speedy", and up to 25 minutes in some cases. I see that the code depends on the behaviour of google.cloud.pubsub.Subscription.pull() in blocking mode. Would modifying the psq code to do its own polling on the unblocked pull() improve that, or would the underlying subscription service still be taking its own sweet time to deliver messages even if we were banging on it every 10 seconds? I can dig into this, but thought you might already have some insights on this problem.

**Comment by jonparrott** [comment]
I think this is a backend issue, but I'm not sure. We're using `pull()` which should be streaming, but even if it wasn't it shouldn't have that much latency.

@tmatsuo @lukesneeringer any ideas?

**Comment by wlongabaugh** [comment]
So if I regularly ping (every ~10 sec) a no-op task for the Worker to execute, I can get the one genuine task I need done delivered in a reasonable time (< 1 minute). It sure looks like PubSub is configured to handle high-throughput messages really, but is falling down with very high latency on low throughput tasks.

**Comment by lukesneeringer** [comment]
> We're using `pull()` which should be streaming, but even if it wasn't it shouldn't have that much latency.

It is not streaming. (A new `streaming_pull` method is planned.)

**Comment by lukesneeringer** [comment]
> So I'm using psq in a light-demand environment, and am encountering abysmal latency on the workers pulling jobs off the queue. As in 10 minutes when things are "speedy", and up to 25 minutes in some cases. I see that the code depends on the behaviour of google.cloud.pubsub.Subscription.pull() in blocking mode. Would modifying the psq code to do its own polling on the unblocked pull() improve that, or would the underlying subscription service still be taking its own sweet time to deliver messages even if we were banging on it every 10 seconds? I can dig into this, but thought you might already have some insights on this problem.

First, thanks for reporting this. I am hoping to dig into improving the PubSub client. Among other things, moving to unblocking methods is a high priority for the PubSub team.

I _expect_ your diagnosis is pretty much accurate. You are not finding out about the task being done because you are not asking the server for it, and there is no automated background ping-and-run-callback at this time.

Can you share with me what you an ideal fix would be for your use case? I am imagining a something like having the subscription accept a callback callable with gets called as messages come in (and of course, we would ask for messages on a cadence with an unblocked call).

**Comment by bsinnottkabam** [comment]
Just want to chime in and say I'm facing same issue as @wlongabaugh. I'm using PubSub+psq as a task queue on flexible environment for rare, long-duration tasks and am often finding 10+ mins for workers to pull new tasks off the queue.

**Comment by wlongabaugh** [comment]
Glad to hear I'm not alone. My workaround is that I stuff a pile (10) of no-op tasks on the queue, then the one I want, followed by another pile of no-op tasks. This flushes the queue immediately. Still hoping for more timely delivery of occasional messages.

**Comment by ajpharrington** [comment]
I am also facing this issue. It takes 2-10 minutes for the worker to start processing the task from the queue. I will try the work around mentioned by @wlongabaugh

**Comment by wlongabaugh** [comment]
After further testing, I find that the arrival of a second message will force the first one out. So it may be enough to follow the desired message immediately with a single empty "ping" job.

**Comment by jonparrott** [comment]
We've been working hard to improve the underlying pubsub library. Hopefully this issue is resolved with #34. But, if it's not, feel free to comment.
