### ISSUE TITLE
psqworker.py:command not found

### ISSUE THREAD

**Issue by andaesa** [GoogleCloudPlatform/psq#25]
This is more to I dont really understand how should I run the worker.
I cloned the repository, install `psq` by `pip install psq`. Before running `run.py`, I tried to run `psqworker` inside the `examples` directory but it there is an error saying that `-bash: psqworker.py: command not found`

Please help me, how should I run `psqworker`?

**Comment by andaesa** [comment]
**UPDATE**
I have figured out how to run it but when I execute `psqworker` inside directory `examples` that contains `run.py` and `tasks.py`, It gives me error saying that 
`Usage: psqworker [OPTIONS] QUEUE

Error: Missing argument "queue".`

What is the meaning of this error? And also I want to ask on what sequence should I run all these files? Is it from `psqworker` --> `python run.py` --> `from tasks import adder \ q.enqueue(adder)` ?

Additional information, 
I run `python run.py` and got the following error

    Traceback (most recent call last):
      File "run.py", line 37, in <module>
    main()
      File "run.py", line 33, in main
    print(r.result(timeout=10))
      File "/Users/andaesa/workspace/google-deploy-spectrophotometer/psq/psq-env/lib/python2.7/site-packages/psq/task.py", line 161, in result
    raise TimeoutError()
    psq.task.TimeoutError

Thank you for your help

**Comment by jonparrott** [comment]
You should run:

```
psqworker run.q
```

In one terminal window. And in a separate terminal run:

```
python run.py
```

**Comment by Cred13** [comment]
The documentation in the readme says the following:

Execute psqworker in the same directory where you tasks are defined:

psqworker.py config.q

Here you say:

psqworker run.q
In one terminal window. And in a separate terminal run:

python run.py


I have tried both and none of them gets the psqworker running. The terminal just stalls.
Do you have any ideas how I can approach this?
