### ISSUE TITLE
Executing a task hangs and fails quietly

### ISSUE THREAD

**Issue by ajpharrington** [GoogleCloudPlatform/psq#28]
I have an async task that I am trying to perform using psq. When I run the task locally, it takes about 5 minutes to execute.

When I deploy it to gcloud and attempt to run it. I can see in the logging that it starts executing, but then it just never finished and there is no logging entry about why it failed. Performing a health check still works, despite the task never finishing.

**Comment by jonparrott** [comment]
Sorry for the late response on this, but we've been working hard to improve the underlying pubsub library. Hopefully this issue is resolved with #34. But, if it's not, feel free to comment.
