### ISSUE TITLE
Worker receive the task but not execute

### ISSUE THREAD

**Issue by shumin** [GoogleCloudPlatform/psq#30]
I'm using psq for running task periodically which works fine. But every few weeks (usually 2 to 3) it receive the task but does not do anything and once it start doing it no further task gets executed. I have checked the logs no error message is there and health check is Ok. For now my only solution is to restart the instance which isn't a very good workaround.

Logs screenshot (notice psq.worker received the task):
<img width="1127" alt="screen shot 2017-09-23 at 12 43 12" src="https://user-images.githubusercontent.com/798074/30772868-dd452900-a05c-11e7-9b24-7e81bec9ad94.png">

requirements.txt:
Flask==0.12.2
google-cloud==0.27.0
gunicorn==19.7.1
oauth2client==4.0.0
six==1.10.0
requests==2.18.3
honcho==1.0.1
psq==0.5.0
google-api-python-client==1.6.2

beautifulsoup4>=4.5.1
arrow==0.10.0
feedparser==5.2.1

Any advice is highly appreciable.
Thanks

**Comment by jonparrott** [comment]
Sorry for the late response on this, but we've been working hard to improve the underlying pubsub library. Hopefully this issue is resolved with #34. But, if it's not, feel free to comment.
