### ISSUE TITLE
Support for google-cloud-pubsub==0.29.0

### ISSUE THREAD

**Issue by aarontp** [GoogleCloudPlatform/psq#32]
It seems that PSQ does not yet support the latest version of the PubSub library which separates the SubscriberClient and the PublisherClient objects (https://github.com/GoogleCloudPlatform/google-cloud-python/pull/3859).  Are there any plans to do so?

In [1]: from google.cloud import pubsub

In [2]: import psq

In [3]: pclient = pubsub.PublisherClient()

In [4]: sclient = pubsub.SubscriberClient()

In [7]: try:
   ...:     q = psq.Queue(pclient)
   ...: except AttributeError as e:
   ...:     print 'ERROR: {0!s}'.format(e)
   ...:     
ERROR: 'Client' object has no attribute 'topic'

In [8]: try:
   ...:     q = psq.Queue(sclient)
   ...: except AttributeError as e:
   ...:     print 'ERROR: {0!s}'.format(e)
   ...:     
ERROR: 'Client' object has no attribute 'topic'

**Comment by jonparrott** [comment]
Yep, we want to, but I'm waiting on a few upstream fixes before I can start working on this.

Thankfully (or perhaps unthankfully), the newest pub/sub includes lots of functionality that was previously in this library.

**Comment by aarontp** [comment]
Thanks!  Just in case anyone else runs across this issue, the temporary workaround that worked for me is to pin these packages (setting google-cloud-core seems to be required too, because there are other upstream changes to where HTTPIterator lives that require it):

google-cloud-pubsub==0.26.0
google-cloud-core==0.26.0

**Comment by jonparrott** [comment]
Closed by #34, will make a new release soon. :)

**Comment by aarontp** [comment]
Yay, thanks!
