### ISSUE TITLE
Make psq Python3.7 compatible

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/psq#40]
```
 File "task.py", line 4, in <module>
    from psq import Queue
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psq/__init__.py", line 24, in <module>
    from .broadcast_queue import BroadcastQueue
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psq/broadcast_queue.py", line 20, in <module>
    from . import queue
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/psq/queue.py", line 37
    name='default', storage=None, extra_context=None, async=True):
```
async and await are now reserved keywords.
https://docs.python.org/3/whatsnew/3.7.html

**Comment by theacodes** [comment]
Sounds like an easy fix, wanna send a PR?

**Comment by VelizarVESSELINOV** [comment]
I agree with you sounds like an easy fix, but sorry very busy with my real job workload, and don't have spare time to provide free help to Google to fix their open source projects. I assume that Google Cloud has enough resources to provide a working version of their 'advanced' hello world with the latest version of Python at least one month after the official release.

**Comment by theacodes** [comment]
No worries. I just prefer to give people in the community a chance to contribute. There's much more value for everyone when we build things together. We'll prioritize and take care of it when we can.

**Comment by theacodes** [comment]
No ETA. Please keep in mind that this is not an officially supported client library, it is a community-supported utility. The underlying Pub/Sub client library is officially supported and works with 3.7.
