### ISSUE TITLE
KeyboardInterrupt not working in Worker

### ISSUE THREAD

**Issue by aarontp** [GoogleCloudPlatform/psq#41]
Whenever I start a worker, it can't be killed with ctrl-c, and so I end up ctrl-z and killing the worker.  This started happening sometime after #34 was submitted (wherein there was a log of other signal processing that got removed).  I'm not sure where the KeyboardInterrupt is going since the 'except KeyboardInterrupt' stanza in the Worker never seems to get called, and setting an explicit signal handler in the calling code doesn't seem to be triggered either.

Here is the code I'm using to call the Worker:
https://github.com/google/turbinia/blob/1f70f2aaef409e33710f5f181ad91b5009b95445/turbinia/client.py#L386

**Comment by theacodes** [comment]
Thanks for reporting, @aarontp! This library is community supported, so if you wanted to send a PR I'd be happy to review. Otherwise, we'll ty to get to this when we can.
