### ISSUE TITLE
Wondering when psq-master (with most recent commit) will be available for pip install on PyPi

### ISSUE THREAD

**Issue by feedertree** [GoogleCloudPlatform/psq#43]
pip install is grabbing the May 30, 2018 release of psq.  I'm wondering when the latest commit (Latest commit 3c51307  on Sep 17, 2018) will be available via pip install.  I just did a pip install of psq and I get the version that is not compatible with python 3.7.  It still has "async" instead of "asynchronous" in it.  Apologies if this is a dumb question.  I honestly don't know how new releases are made available on PyPi (I'm pretty new to all of this).  Thanks for your help.

**Comment by Te-k** [comment]
+1 for that, I end up with the same issue with [this tutorial](https://cloud.google.com/python/getting-started/using-pub-sub), it would be really helpful to issue the last version in pypi

**Comment by busunkim96** [comment]
Contents of master have been released as v0.8.0 to PyPI
https://pypi.org/project/psq/0.8.0/

**Comment by Te-k** [comment]
Thanks @busunkim96 :clap:
