### ISSUE TITLE
psq is not compatible with google-cloud-pubsub 2.0+ version

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/psq#59]
Zero Google maintenance.
A suggestion to kill the project and remove the links to this package from your documentation.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/8209940/94506411-f6c81600-01d2-11eb-85e5-9e74a14a741c.png">

**Comment by meredithslota** [comment]
Agreed — the README notes that this was provided without support, but also, we shouldn't link it in our documentation then. I've submitted a request to remove the link from official documentation, and I appreciate the feedback. Thank you!
