### ISSUE TITLE
[discussion] Late ack

### ISSUE THREAD

**Issue by theacodes** [GoogleCloudPlatform/psq#9]
We should support late acknowledgement of tasks and a way to support extending the ack deadline:

> If a long timeout is set for a long-running task but the task is interrupted prior to completion, it won't be restarted for some time. At the other extreme, if a short timeout is set, a long-running task will be considered incomplete and re-started with another worker. Support for extending timeouts during task execution exists in PubSub, this library should have a way to perform this late_ack.

We should figure out what we want this to look like from a user perspective.

**Comment by seawolf42** [comment]
The first thought that occurs to me is that there are two high-level ways this could look (either/or):

1. The user starts the queue, and optionally provides an auto_extend=True flag that ensures these acks are just always handled automatically as long as the task has not yet returned.
1. The user is running the task, realizes an extension is necessary (perhaps on a monitoring thread), and calls a method o the queue to extend the timeout of the current task.

The former seems like a nicer implementation, but runs the risk of an infinite loop or other errors in the code just running forever; a monitor thread supplied by the user puts more onus on the user to think about what conditions justify continuing to work.

**Comment by jonparrott** [comment]
(1) seems pretty dangerous, as we'd have to have a separate thread running to extend the deadline and there's no way to determine if the task completed successfully or not (halting problem). It seems like (2) might be the most reasonable way.

Perhaps something like:

```python
from psq import extend_deadline

def some_task():
    action_one()
    extend_deadline()
    action_two()
```

**Comment by seawolf42** [comment]
Yeah, agreed. The counter to that is my primary use case specifically involves having to write a monitor thread anyway, as my individual steps can range from a few seconds to many minutes. However, I don't mind doing this within my code... I suspect I'm an outlier.

I would suggest `def extend_deadline(seconds=60)` or some other form of a default value to extend by and a way to override that in the call.

**Comment by jonparrott** [comment]
Absolutely. I think there should also be a way to check if the deadline was exceeded so the task can exit gracefully.

**Comment by seawolf42** [comment]
The first thought that comes to mind is providing a call-back for this purpose in `queue.py`... if it exists, `psq` calls it on deadline exceeded.

    # user's queue.py
    
    q = psq.Queue(
        pubsub_client,
        storage=psq.DatastoreStorage(datastore_client))
    
    def deadline_exceeded():
        # code here to stop the worker gracefully

Alternately `extend_deadline` could throw if the deadline was exceeded prior to the call; then the user could choose to catch and continue or just let their process fail from that point.

**Comment by jonparrott** [comment]
I wouldn't want to handle deadline exceeded at the worker level, just at the task level. If one task exceeds the deadline that doesn't mean the worker has failed, just that task.

> Alternately extend_deadline could throw if the deadline was exceeded prior to the call; then the user could choose to catch and continue or just let their process fail from that point.

That's a great idea.

**Comment by seawolf42** [comment]
That's certainly the easiest to implement... I think that's our best bet.

> I wouldn't want to handle deadline exceeded at the worker level, just at the task level.

Actually, I meant the task, but I acknowledge that can get fairly complicated without passing some sort of context around.

**Comment by seawolf42** [comment]
So then I think what I should implement is the following:

    # globals.py
    
    def extend_deadline(seconds=60):
        check_deadline_exceeded():
        <implementation>
    
    class DeadlineExceededError(Exception): pass
    
    def check_deadline_exceeded():
        if <some tests>:
            raise DeadlineExceededError()

... and then add extend_deadline and DeadlineExceededError to the package exports. Sound reasonable?

**Comment by jonparrott** [comment]
Sounds good.

**Comment by jonparrott** [comment]
[modify_ack_deadline](http://googlecloudplatform.github.io/gcloud-python/stable/pubsub-subscription.html#gcloud.pubsub.subscription.Subscription.modify_ack_deadline) will be the critical function here.

I'd start by not worrying about that just yet - write the basics of that `extend_deadline` and `check_deadline_exceeded` with unit tests and then we can implement the real part of it.

**Comment by seawolf42** [comment]
I'm finally getting a chance to look again at this and am not sure where such unit tests would best belong. I think I need the following tests:
create a mock queue and enqueue a task, then that task calls extend_deadline and makes sure:
check_deadline_exceeded is called
something happens (but not sure where) that in the non-mocked code called modify_ack_deadline
create a mock queue and enqueue a task, then the task calls extend_deadline which mocks the failure in check_deadline_exceeded to test that it raises the exception

I don't think there are any corner cases to test here, either `check_deadline_exceeded` succeeds silently or throws, and `extend_deadline` makes the two calls as expected.

So where should those tests go, in your opinion?

**Comment by jonparrott** [comment]
put them where ever you feel is mostly right for the moment, I can always move them if needed.

**Comment by jonparrott** [comment]
This is now *much* *much* easier with #34. Happy to review any PRs to add this.
